FROM php:8.2.1-fpm-alpine

RUN docker-php-ext-install pdo pdo_mysql

WORKDIR /var/www/html

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

COPY . .

RUN composer install --prefer-dist --no-dev --optimize-autoloader --no-interaction

EXPOSE 9000
